version: "3.8"
name: airpro-gateway

services:
  gateway:
    image: nginx:alpine
    container_name: airpro_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - prod-network
      - staging-network

networks:
  prod-network:
    external: true
    name: airpro-prod_airpro-network
  staging-network:
    external: true
    name: airpro-staging_airpro-staging-network
