version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: dev_postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: AirProV2
    volumes:
      - ./Data/postgres:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./Data/pgadmin:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
