// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518191002_RemoveWarrantyDefaultMonthsFromCompany")]
    partial class RemoveWarrantyDefaultMonthsFromCompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Data.Entities.AirConditioner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Brand")
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<string>("CableSection")
                        .HasColumnType("text")
                        .HasColumnName("cable_section");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("FactoryRefrigerantCharge")
                        .HasColumnType("integer")
                        .HasColumnName("factory_refrigerant_charge");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("IndoorDimensions")
                        .HasColumnType("text")
                        .HasColumnName("indoor_dimensions");

                    b.Property<int?>("Kilowatts")
                        .HasColumnType("integer")
                        .HasColumnName("kilowatts");

                    b.Property<int?>("MaxHeightDifference")
                        .HasColumnType("integer")
                        .HasColumnName("max_height_difference");

                    b.Property<int?>("MaxPipeLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_pipe_length");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OutdoorDimensions")
                        .HasColumnType("text")
                        .HasColumnName("outdoor_dimensions");

                    b.Property<string>("PipeSizeGas")
                        .HasColumnType("text")
                        .HasColumnName("pipe_size_gas");

                    b.Property<string>("PipeSizeLiquid")
                        .HasColumnType("text")
                        .HasColumnName("pipe_size_liquid");

                    b.Property<string>("PowerSupplyLocation")
                        .HasColumnType("text")
                        .HasColumnName("power_supply_location");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("price");

                    b.Property<int?>("RecommendedFuse")
                        .HasColumnType("integer")
                        .HasColumnName("recommended_fuse");

                    b.Property<string>("RefrigerantType")
                        .HasColumnType("text")
                        .HasColumnName("refrigerant_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("WeightIndoor")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("weight_indoor");

                    b.Property<decimal?>("WeightOutdoor")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("weight_outdoor");

                    b.HasKey("Id");

                    b.HasIndex("Brand")
                        .HasDatabaseName("idx_air_conditioners_brand");

                    b.HasIndex("Model")
                        .HasDatabaseName("idx_air_conditioners_model");

                    b.ToTable("air_conditioners");
                });

            modelBuilder.Entity("API.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("address");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("middle_name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("API.Data.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("Bulstat")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bulstat");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("company_name");

                    b.Property<int>("CompanyType")
                        .HasColumnType("integer")
                        .HasColumnName("company_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("HasUsedTrial")
                        .HasColumnType("boolean")
                        .HasColumnName("has_used_trial");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCompanyOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_company_owner");

                    b.Property<bool?>("IsSubscriptionActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_subscription_active");

                    b.Property<bool?>("IsVatRegistered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vat_registered");

                    b.Property<string>("Phone")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("postal_code");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTime?>("SubscriptionCurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_current_period_end");

                    b.Property<int>("SubscriptionPlan")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_plan");

                    b.Property<int>("SubscriptionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_status");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_end_date");

                    b.Property<DateTime?>("TrialStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vat_number");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_companies_is_active");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("API.Data.Entities.InventoryAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<decimal?>("QuantityAfter")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("quantity_after");

                    b.Property<decimal?>("QuantityBefore")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("quantity_before");

                    b.Property<decimal?>("QuantityChanged")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("quantity_changed");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("RelatedMontageId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_montage_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("idx_inventory_audit_action");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("idx_inventory_audit_company_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_inventory_audit_created_at");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("idx_inventory_audit_item_id");

                    b.HasIndex("RelatedMontageId")
                        .HasDatabaseName("idx_inventory_audit_montage_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_inventory_audit_user_id");

                    b.ToTable("inventory_audit_logs");
                });

            modelBuilder.Entity("API.Data.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("text")
                        .HasColumnName("archived_by");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<decimal?>("MinQuantity")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("min_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<string>("Supplier")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("supplier");

                    b.Property<int>("UnitOfMeasure")
                        .HasColumnType("integer")
                        .HasColumnName("unit_of_measure");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("idx_inventory_items_company_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_inventory_items_is_active");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_inventory_items_name");

                    b.HasIndex("Sku")
                        .HasDatabaseName("idx_inventory_items_sku");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("idx_inventory_items_company_name_unique");

                    b.ToTable("inventory_items");
                });

            modelBuilder.Entity("API.Data.Entities.Montage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AirConditionerId")
                        .HasColumnType("uuid")
                        .HasColumnName("air_conditioner_id");

                    b.Property<string>("ClientAddress")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("client_address");

                    b.Property<string>("ClientCity")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_city");

                    b.Property<string>("ClientEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_email");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_name");

                    b.Property<string>("ClientPhone")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("client_phone");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("completion_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomAcBrand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("custom_ac_brand");

                    b.Property<decimal?>("CustomAcKilowatts")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("custom_ac_kilowatts");

                    b.Property<string>("CustomAcModel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("custom_ac_model");

                    b.Property<string>("IndoorUnitSerial")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("indoor_unit_serial");

                    b.Property<DateOnly>("InstallationDate")
                        .HasColumnType("date")
                        .HasColumnName("installation_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("OutdoorUnitSerial")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("outdoor_unit_serial");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("paid_amount");

                    b.Property<int>("PaymentStatus")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("payment_status");

                    b.Property<int>("Status")
                        .HasMaxLength(150)
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("total_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AirConditionerId")
                        .HasDatabaseName("idx_montages_air_conditioner_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("idx_montages_company_id");

                    b.HasIndex("InstallationDate")
                        .HasDatabaseName("idx_montages_installation_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_montages_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_montages_user_id");

                    b.ToTable("montages");
                });

            modelBuilder.Entity("API.Data.Entities.MontageInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<Guid>("MontageId")
                        .HasColumnType("uuid")
                        .HasColumnName("montage_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<decimal>("QuantityUsed")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("quantity_used");

                    b.Property<decimal?>("UnitPriceAtTime")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("unit_price_at_time");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("idx_montage_inventory_item_id");

                    b.HasIndex("MontageId")
                        .HasDatabaseName("idx_montage_inventory_montage_id");

                    b.ToTable("montage_inventory_items");
                });

            modelBuilder.Entity("API.Data.Entities.MontagePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<Guid>("MontageId")
                        .HasColumnType("uuid")
                        .HasColumnName("montage_id");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_name");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.HasKey("Id");

                    b.HasIndex("MontageId")
                        .HasDatabaseName("idx_montage_photos_montage_id");

                    b.HasIndex("MontageId", "DisplayOrder")
                        .HasDatabaseName("idx_montage_photos_order");

                    b.ToTable("montage_photos");
                });

            modelBuilder.Entity("API.Data.Entities.ProcessedStripeEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId");

                    b.ToTable("ProcessedStripeEvents");
                });

            modelBuilder.Entity("API.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("Invalidated")
                        .HasColumnType("boolean")
                        .HasColumnName("invalidated");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("jwt_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean")
                        .HasColumnName("used");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("API.Data.Entities.ReportedProblem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ScreenshotContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("screenshot_content_type");

                    b.Property<string>("ScreenshotFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("screenshot_file_name");

                    b.Property<string>("ScreenshotObjectName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("screenshot_object_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_reported_problems_category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_reported_problems_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_reported_problems_user_id");

                    b.ToTable("reported_problems");
                });

            modelBuilder.Entity("ErrorCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AirConditionerId")
                        .HasColumnType("uuid")
                        .HasColumnName("air_conditioner_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ErrorCodeSeverity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("ErrorName")
                        .HasColumnType("text")
                        .HasColumnName("error_name");

                    b.Property<string>("Solution")
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AirConditionerId")
                        .HasDatabaseName("idx_error_codes_air_conditioner_id");

                    b.HasIndex("Code")
                        .HasDatabaseName("idx_error_codes_error_code");

                    b.ToTable("error_codes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("API.Data.Entities.ApplicationUser", b =>
                {
                    b.HasOne("API.Data.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("API.Data.Entities.InventoryAuditLog", b =>
                {
                    b.HasOne("API.Data.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.Entities.InventoryItem", "InventoryItem")
                        .WithMany("AuditLogs")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.Entities.Montage", "RelatedMontage")
                        .WithMany()
                        .HasForeignKey("RelatedMontageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("InventoryItem");

                    b.Navigation("RelatedMontage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Data.Entities.InventoryItem", b =>
                {
                    b.HasOne("API.Data.Entities.Company", "Company")
                        .WithMany("InventoryItems")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("API.Data.Entities.Montage", b =>
                {
                    b.HasOne("API.Data.Entities.AirConditioner", "AirConditioner")
                        .WithMany()
                        .HasForeignKey("AirConditionerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.Data.Entities.Company", "Company")
                        .WithMany("Montages")
                        .HasForeignKey("CompanyId");

                    b.HasOne("API.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("AirConditioner");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Data.Entities.MontageInventoryItem", b =>
                {
                    b.HasOne("API.Data.Entities.InventoryItem", "InventoryItem")
                        .WithMany("MontageUsages")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Data.Entities.Montage", "Montage")
                        .WithMany("UsedMaterials")
                        .HasForeignKey("MontageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Montage");
                });

            modelBuilder.Entity("API.Data.Entities.MontagePhoto", b =>
                {
                    b.HasOne("API.Data.Entities.Montage", "Montage")
                        .WithMany("Photos")
                        .HasForeignKey("MontageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Montage");
                });

            modelBuilder.Entity("API.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("API.Data.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("API.Data.Entities.ReportedProblem", b =>
                {
                    b.HasOne("API.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErrorCode", b =>
                {
                    b.HasOne("API.Data.Entities.AirConditioner", "AirConditioner")
                        .WithMany("ErrorCodes")
                        .HasForeignKey("AirConditionerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AirConditioner");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("API.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("API.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("API.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Data.Entities.AirConditioner", b =>
                {
                    b.Navigation("ErrorCodes");
                });

            modelBuilder.Entity("API.Data.Entities.Company", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("Montages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("API.Data.Entities.InventoryItem", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("MontageUsages");
                });

            modelBuilder.Entity("API.Data.Entities.Montage", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("UsedMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
